server:
  port: 8088
  servlet:
    context-path: /auth-service

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_service
    username: root
    password: Credable@01
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka


keycloak:
  resource:
  realm:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  ssl-required: none
  credentials:
    secret: TYpmKtoH10iFC8dCGBsrVrj8D3JWMZ5U
  use-resource-role-mappings: true
  bearer-only: true